# MySQL Profile Configuration

spring.datasource.url=jdbc:mysql://mysql-3f6d317a-skillswap2026.k.aivencloud.com:25395/defaultdb?sslMode=REQUIREDss
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_USERNAME}

# JPA/Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable H2 Console for MySQL profile
spring.h2.console.enabled=false

# Auto initialization is handled by ddl-auto=update for MySQL. 
# Alternatively, manual schema.sql execution can be done.
spring.sql.init.mode=never
